MonteCarloPricer: MonteCarlo Class Reference
MonteCarlo Class Reference
#include <MonteCarlo.hpp>
Public Member Functions
MonteCarlo (BlackScholesModel *mod, Option *opt, PnlRng *rng, double fdStep, int nbSamples)
Constructeur de la classe.
~MonteCarlo ()
Destructeur de classe.
void price (double &prix, double &ic)
Calcule le prix de l'option à la date 0.
void price (const PnlMat *past, double t, double &prix, double &ic)
Calcule le prix de l'option à la date t.
void delta (const PnlMat *past, double t, PnlVect *delta)
Calcule le delta de l'option à la date t.
double hedgingPAndL (PnlVect *result, PnlMat *path, int H)
Calcule le profit&loss du portefeuille de couverture.
Data Fields
BlackScholesModel * mod_
Option * opt_
PnlRng * rng_
double fdStep_
int nbSamples_
Private Attributes
PnlMat * spotsMat
PnlMat * shift_path
PnlMat * path
Constructor & Destructor Documentation
MonteCarlo::MonteCarlo (BlackScholesModel * mod, Option * opt, PnlRng * rng, double fdStep, int nbSamples)
Constructeur de la classe.
nombre de tirages Monte Carlo
Parameters
[in] modele Black Scholes
[in] l'option
[in] le générateur
[in] pas de différence finie
[in] nombre de tirages Monte Carlo
Initialisation des variables temporaires
References fdStep_, mod_, nbSamples_, Option::nbTimeSteps_, opt_, path, rng_, shift_path, BlackScholesModel::size_, and spotsMat.
MonteCarlo::~MonteCarlo ()
Destructeur de classe.
References path, shift_path, and spotsMat.
Member Function Documentation
void MonteCarlo::delta (const PnlMat * past, double t, PnlVect * delta)
Calcule le delta de l'option à la date t.
Parameters
[in] past contient la trajectoire du sous-jacent jusqu'à l'instant t
[in] t date à laquelle le calcul est fait
[out] delta contient le vecteur de delta de confiance sur le calcul du delta
References BlackScholesModel::asset(), fdStep_, mod_, nbSamples_, Option::nbTimeSteps_, opt_, path, Option::payoff(), BlackScholesModel::r_, rng_, shift_path, BlackScholesModel::shiftAsset(), BlackScholesModel::size_, and Option::T_.
Referenced by hedgingPAndL(), and main().
double MonteCarlo::hedgingPAndL (PnlVect * result, PnlMat * path, int H)
Calcule le profit&loss du portefeuille de couverture.
Parameters
[out] result contient les profit&loss du portefeuille au cours de la trajectoire
[in] path contient la trajectoire des sous-jacents
Returns
le profit&loss final du portefeuille de couverture
Initialisation
Calcul du prix initial de l'option
Calcul des deltas initiaux
Complétion de la matrice result
Free the memory
References delta(), mod_, Option::nbTimeSteps_, opt_, Option::payoff(), price(), BlackScholesModel::r_, BlackScholesModel::size_, and Option::T_.
Referenced by main().
void MonteCarlo::price (double & prix, double & ic)
Calcule le prix de l'option à la date 0.
Parameters
[out] prix valeur de l'estimateur Monte Carlo
[out] ic largeur de l'intervalle de confiance
Calcul du prix
Confidence interval in 95%
References BlackScholesModel::asset(), mod_, nbSamples_, Option::nbTimeSteps_, opt_, Option::payoff(), BlackScholesModel::r_, rng_, spotsMat, and Option::T_.
Referenced by hedgingPAndL(), and main().
void MonteCarlo::price (const PnlMat * past, double t, double & prix, double & ic)
Calcule le prix de l'option à la date t.
Parameters
[in] past contient la trajectoire du sous-jacent jusqu'à l'instant t
[in] t date à laquelle le calcul est fait
[out] prix contient le prix
[out] ic contient la largeur de l'intervalle de confiance sur le calcul du prix
Price computing
Confidence interval in 95%
References BlackScholesModel::asset(), mod_, nbSamples_, Option::nbTimeSteps_, opt_, Option::payoff(), BlackScholesModel::r_, rng_, spotsMat, and Option::T_.
Field Documentation
double MonteCarlo::fdStep_
pointeur sur le générateur
Referenced by delta(), and MonteCarlo().
BlackScholesModel* MonteCarlo::mod_
Referenced by delta(), hedgingPAndL(), MonteCarlo(), and price().
int MonteCarlo::nbSamples_
pas de différence finie
Referenced by delta(), MonteCarlo(), and price().
Option* MonteCarlo::opt_
pointeur vers le modèle
Referenced by delta(), hedgingPAndL(), MonteCarlo(), and price().
PnlMat* MonteCarlo::path private
Referenced by delta(), MonteCarlo(), and ~MonteCarlo().
PnlRng* MonteCarlo::rng_
pointeur sur l'option
Referenced by delta(), MonteCarlo(), and price().
PnlMat* MonteCarlo::shift_path private
Referenced by delta(), MonteCarlo(), and ~MonteCarlo().
PnlMat* MonteCarlo::spotsMat private
Referenced by MonteCarlo(), price(), and ~MonteCarlo().
The documentation for this class was generated from the following files:
/user/0/.base/charmont/home/Documents/3A/Projet/pricerMonteCarlo/src/MonteCarlo.hpp
/user/0/.base/charmont/home/Documents/3A/Projet/pricerMonteCarlo/src/MonteCarlo.cpp