MonteCarloPricer: BlackScholesModel Class Reference
BlackScholesModel Class Reference
Modèle de Black Scholes.
#include <BlackScholesModel.hpp>
Public Member Functions
BlackScholesModel (int, double, double, PnlVect *, PnlVect *, PnlVect *)
valeurs initiales du sous-jacent
~BlackScholesModel ()
Destructeur de classe.
void asset (PnlMat *path, double T, int nbTimeSteps, PnlRng *rng)
Génère une trajectoire du modèle et la stocke dans path.
void asset (PnlMat *path, double t, double T, int nbTimeSteps, PnlRng *rng, const PnlMat *past)
Calcule une trajectoire du sous-jacent connaissant le passé jusqu' à la date t.
void shiftAsset (PnlMat *shift_path, const PnlMat *path, int d, double h, double t, double timestep)
Shift d'une trajectoire du sous-jacent.
PnlMat * simul_market (int H, double T, PnlRng *rng)
Calcule une simulation de marché
void simul_market (PnlMat *path, double T, int H, PnlRng *rng)
Data Fields
int size_
double r_
nombre d'actifs du modèle
double rho_
taux d'intérêt
PnlVect * sigma_
paramètre de corrélation
PnlVect * spot_
vecteur de volatilités
Protected Attributes
PnlVect * trend_
PnlMat * cholesky
Tendance du modèle.
Private Attributes
PnlVect * G_i
Matrice de Cholesky.
PnlVect * L_d
PnlVect * tempRow
PnlVect * spots_t
Detailed Description
Modèle de Black Scholes.
Constructor & Destructor Documentation
BlackScholesModel::BlackScholesModel (int size, double r, double rho, PnlVect * sigma, PnlVect * spot, PnlVect * trend)
valeurs initiales du sous-jacent
Création de la matrice de Cholesky
Création des vecteurs temporaires
BlackScholesModel::~BlackScholesModel ()
Destructeur de classe.
Suppression des vecteurs temporaires
Member Function Documentation
void BlackScholesModel::asset (PnlMat * path, double T, int nbTimeSteps, PnlRng * rng)
Génère une trajectoire du modèle et la stocke dans path.
Parameters
[out] path contient une trajectoire du modèle. C'est une matrice de taille (nbTimeSteps+1) x d
[in] T maturité
[in] nbTimeSteps nombre de dates de constatation
Simulation de la trajectoire
Referenced by MonteCarlo::delta(), and MonteCarlo::price().
void BlackScholesModel::asset (PnlMat * path, double t, double T, int nbTimeSteps, PnlRng * rng, const PnlMat * past)
Calcule une trajectoire du sous-jacent connaissant le passé jusqu' à la date t.
Parameters
[out] path contient une trajectoire du sous-jacent donnée jusqu'à l'instant t par la matrice past
[in] t date jusqu'à laquelle on connait la trajectoire. t n'est pas forcément une date de discrétisation
[in] nbTimeSteps nombre de pas de constatation
[in] T date jusqu'à laquelle on simule la trajectoire
[in] past trajectoire réalisée jusqu'a la date t
Copie de la trajectoire passée dans la trajectoire totale
Sauvegarde des spots
Simulation de la trajectoire
void BlackScholesModel::shiftAsset (PnlMat * shift_path, const PnlMat * path, int d, double h, double t, double timestep)
Shift d'une trajectoire du sous-jacent.
Parameters
[in] path contient en input la trajectoire du sous-jacent
[out] shift_path contient la trajectoire path dont la composante d a été shiftée par (1+h) à partir de la date t.
[in] t date à partir de laquelle on shift
[in] h pas de différences finies
[in] d indice du sous-jacent à shifter
[in] timestep pas de constatation du sous-jacent
Referenced by MonteCarlo::delta().
PnlMat * BlackScholesModel::simul_market (int H, double T, PnlRng * rng)
Calcule une simulation de marché
Parameters
[in] H le nombre de dates
[in] T la maturité
[in] rng le générateur aléatoire
Simulation de la trajectoire
Referenced by main().
void BlackScholesModel::simul_market (PnlMat * path, double T, int H, PnlRng * rng)
Field Documentation
PnlMat* BlackScholesModel::cholesky protected
Tendance du modèle.
PnlVect* BlackScholesModel::G_i private
Matrice de Cholesky.
Déclaration ici afin de limiter les créations et suppressions à chaque appel
PnlVect* BlackScholesModel::L_d private
double BlackScholesModel::r_
nombre d'actifs du modèle
Referenced by MonteCarlo::delta(), MonteCarlo::hedgingPAndL(), and MonteCarlo::price().
double BlackScholesModel::rho_
taux d'intérêt
PnlVect* BlackScholesModel::sigma_
paramètre de corrélation
int BlackScholesModel::size_
Referenced by MonteCarlo::delta(), MonteCarlo::hedgingPAndL(), and MonteCarlo::MonteCarlo().
PnlVect* BlackScholesModel::spot_
vecteur de volatilités
PnlVect* BlackScholesModel::spots_t private
PnlVect* BlackScholesModel::tempRow private
PnlVect* BlackScholesModel::trend_ protected
The documentation for this class was generated from the following files:
/user/0/.base/charmont/home/Documents/3A/Projet/pricerMonteCarlo/src/BlackScholesModel.hpp
/user/0/.base/charmont/home/Documents/3A/Projet/pricerMonteCarlo/src/BlackScholesModel.cpp