MonteCarloPricer: /user/0/.base/charmont/home/Documents/3A/Projet/pricerMonteCarlo/src/Pricer.cpp File Reference
Pricer.cpp File Reference
#include <iostream>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "pnl/pnl_matrix.h"
#include "pnl/pnl_random.h"
#include "pnl/pnl_vector.h"
#include "parser.hpp"
#include "BlackScholesModel.hpp"
#include "MonteCarlo.hpp"
#include "OptionAsian.hpp"
#include "OptionBasket.hpp"
#include "OptionPerformance.hpp"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References MonteCarlo::delta(), Param::extract(), MonteCarlo::hedgingPAndL(), MonteCarlo::price(), and BlackScholesModel::simul_market().